### ISSUE TITLE
24 tests fail

### ISSUE THREAD

**Issue by yurivict** [psf/cachecontrol#331] opened 2024-02-03 07:45 UTC
[log](https://freebsd.org/~yuri/py-cachecontrol-0.14.0-tests.log)

Version: 0.14.0
Python-3.9
FreeBSD 14.0

**Comment by woodruffw** [comment] 2024-02-03 08:47
From that log, the failing tests really just look like mypy errors (not actual unit test failures).

Could you provide some more context here? We'll make an effort to diagnose those, but they aren't indicative of regressions or errors in the release itself.

**Comment by yurivict** [comment] 2024-02-03 08:49
This happened in the context of the FreeBSD port framework - the port is being tested.

These mypy-related packages are installed:
```
py39-mypy-1.8.0                Optional static typing for Python
py39-mypy_extensions-1.0.0     Experimental type system extensions for programs
py39-pytest-mypy-0.10.3        Mypy static type checker plugin for pytest
```

**Comment by woodruffw** [comment] 2024-02-03 08:53
Okay, thanks for the extra context. I'm not sure if we do (or ever have) supported a `pytest-mypy` path -- I believe our CI runs `tox -e mypy` or similar. It's possible that running it through the `pytest` plugin causes some configuration settings to be dropped, causing these errors.

**Comment by woodruffw** [comment] 2024-07-09 21:33
I can't reproduce this locally, so I'm going to close this out. Please make sure you're using `tox -e mypy` to run typechecking rather than pytest, since that isn't a route we test!

**Closed by woodruffw** 2024-07-09 21:33 UTC
Labels: information needed
